config/routes.rb
Rails.application.routes.draw do

  resources :lessors

  resources :units

  devise_for :tenants
  
  root to: "home#home"

end

app/models/lease.rb
# Represents a Tenant Leasing a Unit
#
# Attributes
# tenant_id:: Associated `Tenant`
# unit_id:: Associated `Unit`
# payment_amount:: Amount to pay towards rent
# active:: Is this lease active?
class Lease < ActiveRecord::Base

  # Assocations
  belongs_to :tenant
  belongs_to :unit

end

app/models/lessor.rb
# Represents a payee (the lessor) of a `Unit`
#
# Attributes
# name:: Name of lessor
# street_address:: Address to remit payment
# secondary_address::
# city::
# region::
# postal_code::
class Lessor < ActiveRecord::Base

  # Assocations
  has_many :units

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  # Associations
  has_many :leases
  
end

app/models/unit.rb
# Represents a Unit which can be Leased by a Tenant
#
# Attributes
# lessor_id:: Associated `Lessor`
# address:: Address of unit
# unit_number:: Unit number (e.g. Apt 2)
# city::
# state::
# postal_code::
# total_rent:: Total rent for unit
# payment_day:: Day of month to expect payment
class Unit < ActiveRecord::Base

  # Associations
  belongs_to :lessor
  has_many :leases
  has_many :tenants, through: :leases # TODO: Scope active

  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/lessors_controller.rb
class LessorsController < ApplicationController
  before_action :set_lessor, only: [:show, :edit, :update, :destroy]

  # GET /lessors
  def index
    @lessors = Lessor.all
  end

  # GET /lessors/1
  def show
  end

  # GET /lessors/new
  def new
    @lessor = Lessor.new
  end

  # GET /lessors/1/edit
  def edit
  end

  # POST /lessors
  def create
    @lessor = Lessor.new(lessor_params)

    if @lessor.save
      redirect_to @lessor, notice: 'Lessor was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lessors/1
  def update
    if @lessor.update(lessor_params)
      redirect_to @lessor, notice: 'Lessor was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lessors/1
  def destroy
    @lessor.destroy
    redirect_to lessors_url, notice: 'Lessor was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lessor
      @lessor = Lessor.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lessor_params
      params.require(:lessor).permit(:name, :street_address, :secondary_address, :city, :region, :postal_code)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  def index
    @units = Unit.all
  end

  # GET /units/1
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to @unit, notice: 'Unit was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /units/1
  def update
    if @unit.update(unit_params)
      redirect_to @unit, notice: 'Unit was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /units/1
  def destroy
    @unit.destroy
    redirect_to units_url, notice: 'Unit was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def unit_params
      params.require(:unit).permit(:lessor_id, :address, :unit_number, :city, :state, :postal_code, :total_rent, :payment_day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessors_helper.rb
module LessorsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/home/home.html.haml
%h1 Home#home
%p Find me in app/views/home/home.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Haven
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    .container
      -# Alerts
      .notice= notice
      .alerts= alert

      -# Nav bar
      %nav.navbar
        .container-fluid
          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              - if tenant_signed_in?
                .li
                  %a Your Account
              - else
                .li
                  %a{href: new_tenant_registration_path} Sign-up
                .li
                  %a{href: new_tenant_session_path} Login

      -# Main page content
      = yield

app/views/lessors/_form.html.haml
= form_for @lessor do |f|
  - if @lessor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lessor.errors.count, "error")} prohibited this lessor from being saved:"
      %ul
        - @lessor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :street_address
    = f.text_field :street_address
  .field
    = f.label :secondary_address
    = f.text_field :secondary_address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :region
    = f.text_field :region
  .field
    = f.label :postal_code
    = f.text_field :postal_code
  .actions
    = f.submit 'Save'

app/views/lessors/edit.html.haml
%h1 Editing lessor

= render 'form'

= link_to 'Show', @lessor
\|
= link_to 'Back', lessors_path

app/views/lessors/index.html.haml
%h1 Listing lessors

%table
  %tr
    %th Name
    %th Street address
    %th Secondary address
    %th City
    %th Region
    %th Postal code
    %th
    %th
    %th

  - @lessors.each do |lessor|
    %tr
      %td= lessor.name
      %td= lessor.street_address
      %td= lessor.secondary_address
      %td= lessor.city
      %td= lessor.region
      %td= lessor.postal_code
      %td= link_to 'Show', lessor
      %td= link_to 'Edit', edit_lessor_path(lessor)
      %td= link_to 'Destroy', lessor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Lessor', new_lessor_path

app/views/lessors/new.html.haml
%h1 New lessor

= render 'form'

= link_to 'Back', lessors_path

app/views/lessors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @lessor.name
%p
  %b Street address:
  = @lessor.street_address
%p
  %b Secondary address:
  = @lessor.secondary_address
%p
  %b City:
  = @lessor.city
%p
  %b Region:
  = @lessor.region
%p
  %b Postal code:
  = @lessor.postal_code

= link_to 'Edit', edit_lessor_path(@lessor)
\|
= link_to 'Back', lessors_path

app/views/tenants/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/units/_form.html.haml
= form_for @unit do |f|
  - if @unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@unit.errors.count, "error")} prohibited this unit from being saved:"
      %ul
        - @unit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :lessor_id
    = f.number_field :lessor_id
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :unit_number
    = f.text_field :unit_number
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :postal_code
    = f.text_field :postal_code
  .field
    = f.label :total_rent
    = f.text_field :total_rent
  .field
    = f.label :payment_day
    = f.number_field :payment_day
  .actions
    = f.submit 'Save'

app/views/units/edit.html.haml
%h1 Editing unit

= render 'form'

= link_to 'Show', @unit
\|
= link_to 'Back', units_path

app/views/units/index.html.haml
%h1 Listing units

%table
  %tr
    %th Lessor
    %th Address
    %th Unit number
    %th City
    %th State
    %th Postal code
    %th Total rent
    %th Payment day
    %th
    %th
    %th

  - @units.each do |unit|
    %tr
      %td= unit.lessor_id
      %td= unit.address
      %td= unit.unit_number
      %td= unit.city
      %td= unit.state
      %td= unit.postal_code
      %td= unit.total_rent
      %td= unit.payment_day
      %td= link_to 'Show', unit
      %td= link_to 'Edit', edit_unit_path(unit)
      %td= link_to 'Destroy', unit, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Unit', new_unit_path

app/views/units/new.html.haml
%h1 New unit

= render 'form'

= link_to 'Back', units_path

app/views/units/show.html.haml
%p#notice= notice

%p
  %b Lessor:
  = @unit.lessor_id
%p
  %b Address:
  = @unit.address
%p
  %b Unit number:
  = @unit.unit_number
%p
  %b City:
  = @unit.city
%p
  %b State:
  = @unit.state
%p
  %b Postal code:
  = @unit.postal_code
%p
  %b Total rent:
  = @unit.total_rent
%p
  %b Payment day:
  = @unit.payment_day

= link_to 'Edit', edit_unit_path(@unit)
\|
= link_to 'Back', units_path